apiVersion: v1
kind: Pod
metadata:
  name: mcda-db-init
  namespace: drugis
  labels:
    app: mcda-db-init
spec:
  initContainers:
    - name: wait-for-db
      image: postgres:10.8
      env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
      command: ['sh', '-c']
      args:
        - until psql -h postgres -c  "select version();"; do echo waiting for postgres; sleep 2; done;
    - name: get-mcda-schema
      image: busybox:1.28
      command:
        [
          'sh',
          '-c',
          'wget -O /schema-data/mcda-schema.sql https://raw.githubusercontent.com/drugis/mcda-elicitation-web/master/database.pg.sql'
        ]
      volumeMounts:
        - name: schema-data
          mountPath: /schema-data
    - name: create-mcda-user
      image: postgres:10.8
      env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: MCDAWEB_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MCDAWEB_DB_PASSWORD
      command: ['sh', '-c']
      args:
        - psql -h postgres -c  "CREATE USER mcda WITH PASSWORD '$(MCDAWEB_DB_PASSWORD)'" -c  "CREATE database mcda encoding 'utf-8'"
  restartPolicy: Never
  containers:
    - name: run-liquibase
      image: webdevops/liquibase:postgres
      env:
        - name: LIQUIBASE_URL
          value: 'jdbc:postgresql://postgres:5432/mcda'
        - name: LIQUIBASE_USERNAME
          value: 'mcda'
        - name: LIQUIBASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MCDAWEB_DB_PASSWORD
        - name: LIQUIBASE_CHANGELOG
          value: '/schema-data/mcda-schema.sql'
      args:
        - 'update'
      volumeMounts:
        - name: schema-data
          mountPath: /schema-data
  volumes:
    - name: schema-data
      emptyDir: {}
