apiVersion: v1
kind: Service
metadata:
  name: patavi-server-composed
  namespace: mcda
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: patavi-server-composed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patavi-server-composed
  namespace: mcda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patavi-server-composed
  template:
    metadata:
      labels:
        app: patavi-server-composed
    spec:
      volumes:
        - name: certificates
          configMap:
            name: certificates
            items:
              - key: patavi-server-crt.pem
                path: server-crt.pem
              - key: patavi-server-key.pem
                path: server-key.pem
              - key: ca-crt.pem
                path: ca-crt.pem
      containers:
        - name: patavi-server-composed
          image: addis/patavi-server
          volumeMounts:
            - name: certificates
              mountPath: /var/lib/patavi/ssl
          envFrom:
            - configMapRef:
                name: patavi-settings
          env:
            - name: PATAVI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: PATAVI_DB_PASSWORD
          ports:
            - name: patavi-server
              containerPort: 3000
