name: test docker run

on:
  push:
    branches: github/testRunDocker

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['12']
        os: [ubuntu-16.04]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: drugis/patavi
          path: patavi

      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.deployPrivateKey }}

      - name: run postgres
        run: docker run -e POSTGRES_PASSWORD=develop postgres &

      - name: run rabbit
        run: docker run -d --hostname my-rabbit --name my-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3-management &

      - name: list patavi?
        run: ls patavi

      - name: stop docker containers
        run: docker ps -a
