name: test docker run

on:
  push:
    branches: github/testRunDocker

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['12']
        os: [ubuntu-16.04]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: develop
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.deployPrivateKey }}

      - name: fetch schema
        run: curl https://raw.githubusercontent.com/drugis/patavi/master/server/schema.sql -o patavi.schema.sql

      - name: setup patavi database
        run: |
          docker exec ${{ job.services.postgres.id }} psql -U postgres -c "CREATE USER patavi WITH PASSWORD 'develop'"
          docker exec ${{ job.services.postgres.id }} psql -U postgres -c "CREATE DATABASE patavi ENCODING 'utf-8' OWNER patavi"

      - name: initialize patavi database
        run: |
          docker cp patavi.schema.sql ${{ job.services.postgres.id }}:/patavi.schema.sql
          docker exec ${{ job.services.postgres.id }} psql -U patavi -f patavi.schema.sql

      - name: run rabbit
        run: docker run -d --hostname my-rabbit --name my-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3-management

      - name: run patavi server
        run: |
          docker run -d --name patavi-server \
          --link my-rabbit:rabbit \
          -e PATAVI_BROKER_HOST=guest:guest@rabbit \
          -p 3000:3000 \
          -e PATAVI_SELF=//localhost:3000 \
          -e PATAVI_PORT=3000 \
          -e PATAVI_DB_HOST=localhost \
          -e PATAVI_DB_NAME=patavi \
          -e PATAVI_DB_USER=patavi \
          -e PATAVI_DB_PASSWORD=develop \
          addis/patavi-server

      - name: build and run patavi worker
        run: |
          cd R
          docker build --tag addis/patavi-smaa-worker .
          docker run -d --link my-rabbit:rabbit -e PATAVI_BROKER_HOST=rabbit --name patavi-mcda-worker addis/patavi-smaa-worker

      - name: stop docker containers
        run: docker ps -a
